### ISSUE TITLE
Can we drop `bem-core`, and use ranges for `bem-components` libraries?

### ISSUE THREAD

**Issue by zxqfox** [verybigman/bem-content#71]
Since `bem-components` knows about stable and compatible version of `bem-core` we can safely drop that dependency to decrease version resolution troubles.

Also we can use ranges for `bem-components`: https://github.com/npm/node-semver#ranges — since semver guarantees that 2.0.x branch shouldn't change their behaviour (only bug fixes and minor or optional features).

**Comment by verybigman** [comment]
Yes, we can:)
